name: "CLA Assistant"
on: [push, pull_request, workflow_dispatch]

  

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Run        
        run: python run.py